### ISSUE TITLE
Can not read from /dev/usbtmc2

### ISSUE THREAD

**Issue by jbrumf** [Teuniz/DSRemote#12]
I am having problems getting DSRemote to work with USB, although it works fine with the LAN interface.

I have a Rigol DS1074Z with firmware 00.04.04.01.01 (aka 00.04.04.SP1) and a Dell Optiplex 7040 running Ubuntu 16.10 with kernel 4.8.0-27-generic. DSRemote is git commit d1940c3ab2 (13 November 2016).

My UDEV rules are as follows:
```
SUBSYSTEMS=="usb", ACTION=="add", ATTRS{idVendor}=="1ab1", ATTRS{idProduct}=="04ce", GROUP="usbtmc", MODE="0660"
KERNEL=="usbtmc/*", ATTRS{idVendor}=="1ab1", ATTRS{idProduct}=="04ce", GROUP="usbtmc", MODE="0660"
KERNEL=="usbtmc[0-9]*", ATTRS{idVendor}=="1ab1", ATTRS{idProduct}=="04ce", GROUP="usbtmc", MODE="0660"
```
I belong to the group usbtmc and the following device file appears:
```
$ ls -l /dev/usbtmc*
crw-rw---- 1 root usbtmc 180, 2 Nov 13 13:08 /dev/usbtmc2
```
When I start DSRemote, I select /dev/usbtmc2 in settings, then connect from the device menu. The following appears in the terminal window:
```
$ dsremote
tmc_dev write: *IDN?
```
An error dialog appears with "Can not read from /dev/usbtmc2

lsusb shows the following:
```
$ lsusb
Bus 002 Device 002: ID 1058:10b8 Western Digital Technologies, Inc. Elements Portable (WDBU6Y, WDBUZG)
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 8087:0a2b Intel Corp. 
Bus 001 Device 004: ID 05ac:0267 Apple, Inc. 
Bus 001 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 013: ID 1ab1:04ce Rigol Technologies 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

$ lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/10p, 5000M
    |__ Port 4: Dev 2, If 0, Class=Mass Storage, Driver=usb-storage, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/16p, 480M
    |__ Port 1: Dev 13, If 0, Class=Application Specific Interface, Driver=usbtmc, 480M
    |__ Port 2: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 2: Dev 3, If 1, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 2: Dev 3, If 2, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 7: Dev 4, If 2, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 7: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 7: Dev 4, If 1, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 9: Dev 5, If 0, Class=Wireless, Driver=btusb, 12M
    |__ Port 9: Dev 5, If 1, Class=Wireless, Driver=btusb, 12M
```

Any help would be welcome.

**Comment by Teuniz** [comment]
Why did you add the udev rules?
How many instruments that uses usbtmc protocol are connected to your pc via usb?
Why do you use usbtmc2 instead of usbtmc0?

**Comment by jbrumf** [comment]
Many thanks for the fast response
> Why did you add the udev rules?

To give permission to access the device without being root. I tried removing the rules file but it still did not work.
```
$ ls -l /dev/usbtmc2 
crw------- 1 root root 180, 2 Nov 13 16:38 /dev/usbtmc2
```
> How many instruments that uses usbtmc protocol are connected to your pc via usb?

Just the Rigol oscilloscope. The other devices plugged into USB ports are a Logitech mouse, Apple keyboard and a USB disk.

> Why do you use usbtmc2 instead of usbtmc0?

When I plug in the scope USB lead, one device appears in /dev and that is usbtmc2. The number depends on which USB port I plug it in to and which order I plug in the devices. If I unplug everything else, plug in the scope followed by the keyboard and mouse, I get usbtmc0, but it still doesn't work.

Incidentally, the following works from the command line:
```
echo ':STOP' > /dev/usbtmc0
```
However, the 'cat' in the following returns immediately:
```
$ echo '*IDN?' > /dev/usbtmc0
$ cat /dev/usbtmc0
$
```

**Comment by Teuniz** [comment]
First, the fact that the usbtmc device can only be accessed by root is a bug in the configuration of the OS.
Group id of /dev/usbtmc* should be "usbtmc". Please file a bug report for this.
For comparison, imagine that the serial port could only be used by root...

Second, I'm still using Opense 13.2 which uses an older kernel 3.16.
Kernel 4.8 has a lot of modifications in the usbtmc driver which could have broken compatibility.
See:
http://lxr.free-electrons.com/source/drivers/usb/class/usbtmc.c?v=3.16
and
http://lxr.free-electrons.com/source/drivers/usb/class/usbtmc.c?v=4.8

Could you try to install Opensuse 13.2 in VirtualBox to see if that helps?

**Comment by jbrumf** [comment]
I will try Opensuse 13.2 and let you know the outcome.

Thanks again

**Comment by jbrumf** [comment]
I tried dsremote in an opensuse 13.2 VirtualBox guest machine, as you suggested, but the problem remained.

```
$ uname -a
Linux linux-79dl 3.16.7-48-desktop #1 SMP PREEMPT Wed Oct 26 18:09:22 UTC 2016 (8c027f6) x86_64 x86_64 x86_64 GNU/Linux
```

As before:

* I had to add the udev rules to make usbtmc accessible to the group usbtmc.
* I got the message "Can not read from device /dev/usbtmc0" when I tried to connect
* The terminal shows "tmc_dev write:*IDN?"
* The scope appears in "lsusb" as expected
* echo ":STOP" > /dev/usbtmc0 works

Finally,  I tried running the opensuse guest on a different computer (iMac) with the same results.

The scope is OK because I can control it with usbtmc using the python-usbtmc library.

**Comment by Teuniz** [comment]
I just installed openSuse Leap 42.2 with kernel 4.4.
Apart from a permission problem, DSRemote runs fine using /dev/usbtmc0
To solve the permission problem, do the following:
Create a file /lib/udev/rules.d/30-usbtmc.rules that contains the following:
`####################################################################################
# USBTMC instruments

# Rigol Technologies  DS1000Z series
SUBSYSTEMS=="usb", ACTION=="add", ATTRS{idVendor}=="1ab1", ATTRS{idProduct}=="04ce", GROUP="usbtmc", MODE="0660"

# Devices
KERNEL=="usbtmc/*",       MODE="0660", GROUP="usbtmc"
KERNEL=="usbtmc[0-9]*",   MODE="0660", GROUP="usbtmc"
####################################################################################
`

**Comment by pavel-kirienko** [comment]
I am running Mint 18 with Linux 4.4.0-21-generic, otherwise my setup is similar to that of @jbrumf, and I am observing exactly the same behavior - DSRemote fails to connect to `/dev/usbtmc1` with a read error.

**Comment by Teuniz** [comment]
Pavel-kirienko, does it work via LAN connection?

**Comment by pavel-kirienko** [comment]
Unfortunately I can't connect it via LAN at the moment, sorry.

**Comment by Teuniz** [comment]
I can't reproduce the problem here.
After switching on the scope, after 30 seconds, run the command dmesg in a terminal and copy & paste the last lines here. I need to see the lines starting from "new high-speed USB device number 4 using ehci-pci" and everything after that.

**Comment by pavel-kirienko** [comment]
Here:

```
[81251.626023] usb 1-3: new high-speed USB device number 5 using ehci-pci
[81251.758455] usb 1-3: config 1 interface 0 altsetting 0 endpoint 0x81 has an invalid bInterval 80, changing to 10
[81251.758459] usb 1-3: config 1 interface 0 altsetting 0 bulk endpoint 0x82 has invalid maxpacket 64
[81251.758461] usb 1-3: config 1 interface 0 altsetting 0 bulk endpoint 0x3 has invalid maxpacket 64
[81251.758932] usb 1-3: New USB device found, idVendor=1ab1, idProduct=04ce
[81251.758935] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[81251.758937] usb 1-3: Product: DS1000Z Series
[81251.758938] usb 1-3: Manufacturer: Rigol Technologies. 
[81251.758940] usb 1-3: SerialNumber: DS1ZA161450675
```

Trying to connect to the scope from DSRemote does not produce any additional dmesg entries. The warning messages about incorrect USB parameters do look alarming. I am using firmware version 00.04.00.

**Comment by Teuniz** [comment]
It's better not to show the complete serial number of your scope publicly on the internet.
I advise you to edit your last message and change the last six digits of the serial number into x's.

After that, give me the output of the command uname -a

**Comment by pavel-kirienko** [comment]
Thanks. Here's the output of `uname -a`:

```
Linux pavel-workstation 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Teuniz** [comment]
I'm using the same kernel version and despite I see the same kernel error messages, it works fine here.

Facts:
The firmware in the scope uses High-Speed USB protocol and
sets the max packet size of the bulk endpoint to 64 bytes.
This is a protocol violation.
A bulk endpoint in a high-speed device MUST have a max packet size of 512.

My theory is that some EHCI USB host controller chips on pc/laptop motherboards don't act well
with that. This explains why on some hardware it doesn't work.
The only solution is that Rigol fixes this in their firmware.

Please file a bugreport at Rigol. The more people complain, the more likely they'll will do
something about it.

**Comment by pavel-kirienko** [comment]
Thanks, I submitted a support request via their website and gave them a link to this discussion. Let's hope they can help.

**Comment by jbrumf** [comment]
I think this issue can be closed now, as I am pretty certain that the problem is nothing to do with DSRemote.

USBTMC works fine using the Linux kernel driver and the USB2 (ehci) ports on a Raspberry Pi 2, but doesn't work with my Dell that only has USB3 (xhci) ports. I suspect it is related some combination of the controller chip, Linux xhci driver and the 64-byte max packet size.

Thanks for your help.
