### ISSUE TITLE
commenting out stropts.h in tmc_lan.c

### ISSUE THREAD

**Issue by lambcutlet** [Teuniz/DSRemote#13]
this program is superb I use it with a DS1054z via lan

i use fedora as an OS, as such i had to jump through some hoops to get it to work.
to install, your instructions are:
qmake           
make -j16
sudo make install

qmake in fedora is 'qmake-qt4', to run this you need to install 'qt-devel'
make -j16 - initially failed until i installed 'gcc-c++' (gcc-c++ replaces g++) this improved the situation however it continues to fail reporting no 'stropts.h' file. It appears this header is not included in fedora. I commented out 'stropts.h' from file 'tmc_lan.c' to make it work for me.
will commenting out 'stropts.h' cause an issue?

**Comment by Teuniz** [comment]
I removed the reference to stropts.h because it doesn't seem to be necessary.
I updated the source and also the compile instructions.
Thank you for reporting this issue.
