### ISSUE TITLE
Unable to connect to Rigol DS1054Z via USB (Firmware Version 00.04.04.SP3)

### ISSUE THREAD

**Issue by HoracioDos** [Teuniz/DSRemote#15]
I can't connect to Rigol DS1054Z Firmware Version 00.04.04.SP3 via USB. 

When I click connect a popup message says "cannot read from device /dev/usbtmc1" and there's also an error in the command line.  "tmc_dev write: *IDN?"

if I run echo ":STOP" > /dev/usbtmc1 It works fine.

This is my config: 

lsb_release -a
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

uname -a
Linux U47VC 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

modinfo usbtmc
filename:       /lib/modules/4.4.0-53-generic/kernel/drivers/usb/class/usbtmc.ko
license:        GPL
srcversion:     8A1D71863801CA6BE71EE57
alias:          usb:v*p*d*dc*dsc*dp*icFEisc03ip01in*
alias:          usb:v*p*d*dc*dsc*dp*icFEisc03ip00in*
depends:        
intree:         Y
vermagic:       4.4.0-53-generic SMP mod_unload modversions

udev rules file: /etc/udev/rules.d/51-usbtmc.rules
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1ab1", ATTRS{idProduct}=="04ce", GROUP="dialout", MODE="0660"

ls -la /dev/usbtmc1
crw-rw---- 1 root dialout 180, 1 Apr 28 16:37 /dev/usbtmc1

Sigrok works fine on the same device.

**Comment by Teuniz** [comment]
This problem is reported by other people as well and it is not the fault of DSRemote but the firmware
of the scope. For an explanation, look here: https://github.com/Teuniz/DSRemote/issues/12#issuecomment-283940080

**Comment by momu** [comment]
I recently found out that it will not work with a USB3 port. Have you tried a USB2 port?

**Comment by andmarti1424** [comment]
Hello! This still isnt fixed in USB3? Thanks!

**Comment by Teuniz** [comment]
Rigol said that it's too hard to fix.
What you could try is to put an old USB-hub between the scope and your pc.

**Comment by andmarti1424** [comment]
I see. That's bad news. Thanks for your help.
