### ISSUE TITLE
Unknown identification string from device

### ISSUE THREAD

**Issue by imcnanie** [Teuniz/DSRemote#16]
When trying to connect over LAN. I get the following error: 

Received an unknown identification string from device:

RIGOL TECHNOLOGIES,DS1104Z Plus,DS1ZC182801561,00.04.03.SP2

Any idea how to fix it?
![dsremoteee](https://cloud.githubusercontent.com/assets/4652417/26740428/5df15c80-478a-11e7-95b9-c629b5a60f0d.png)

**Comment by imcnanie** [comment]
Also getting "tmc_lan write: *IDN?" in the terminal. Running Ubuntu 16.04.

**Comment by Teuniz** [comment]
I added it to the device list. Could you pull again and recompile?
Let me know if it works.

**Comment by imcnanie** [comment]
Yes! It works great. Thank you!
