### ISSUE TITLE
Fixed format LAN address entry is too restrictive

### ISSUE THREAD

**Issue by cpavlina** [Teuniz/DSRemote#17]
Why does the LAN address entry force me to type four octets? Many network configurations can resolve hostnames for local devices, I don't want to have to figure out and type in the IP address for my oscilloscope - especially when the address _isn't reserved_... Surely the underlying network library can take an arbitrary hostname directly and resolve it.

**Comment by Teuniz** [comment]
From now on you can choose to use a hostname or an IP-address for the LAN connection.

**Comment by Teuniz** [comment]
Closed because the issue has been resolved.
