### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by x8-999-github** [Teuniz/DSRemote#19]
Hello,

It would be very nice to allow allow saving waveforms like
https://github.com/RoGeorge/DS1054Z_screen_capture/blob/master/OscScreenGrabLAN.py#L189 does

With kind regards

**Comment by Teuniz** [comment]
CSV is an inferior format that takes way too much space. It's only used as a kind of last resort when better formats/standards are not available or implemented.
DSRemote saves the files in EDF. A format that can be opened in all kinds of software for analysis like Scilab, Octav, matlab. If you insist to use CSV format, the free EDFbrowser software can convert EDF files to CSV files.
