### ISSUE TITLE
add OSX support (network only) fails after some basic steps

### ISSUE THREAD

**Issue by technogeeky** [Teuniz/DSRemote#2]
@Teuniz:

Your software works fine at home, on Linux. But I am using my OSX-based laptop with my Rigol 1054z scope on the road and so I started to see what is necessary to get things to work in OSX.

As far as getting it to compile, it's not that bad. I have a repository (not uploaded yet, due to github auth) with all of the necessary changes (there are only four or five small things). The overall process of installing should be pretty easy, too. I currently have the program starting just fine.

Since there is no OSX usbtmc driver, I was looking at porting it *or* wrapping python-usbtmc back to C++, but then I realized that I should be able to comment out/ignore the USB part, and use the network part.

This indeed worked, but the data that the program is sending seems to be malformed. There are "zero window" TCP packets, and duplicate ACK TCP packets. Furthermore, none of the packets actually contain the message put in the buffer, namely [it fails here](https://github.com/Teuniz/DSRemote/blob/master/mainwindow.cpp#L155).

I have wireshark captures of the successful packet interactions on Linux, and the unsuccessful packet interactions on OSX.

I suspect there is a problem with file descriptors or timeouts, or how select() behaves on OSX.

I am willing to keep at this as long as you're interested. I know for a fact that another (pure python) program can connect to the scope and do FFT stuff (though I haven't tried network there yet).

Do you have an OSX machine to play with to work with me? Are you aware of any other people wanting to use OSX?

Thanks,
-tg

**Comment by Teuniz** [comment]
Hello tg,

Thank you for your interest but I don't have a Mac.
Apart from that, I don't have enough spare time to port and/or support all my software projects to other platforms.
Some time ago I decided to exclusively support Linux.
Ofcourse, you are free to do what you want with the source (within the rules of the GPL) but unfortunately, I can't help you.

Kind Regards,

Teunis

**Comment by Teuniz** [comment]
Instead of trying to port DSRemote to OSX, you could use Virtualbox.
That way you can also use USB connection.
