### ISSUE TITLE
Unable to connect to Rigol DS1104Z via USB or LAN (Firmware Version 00.04.04.SP3) 

### ISSUE THREAD

**Issue by momu** [Teuniz/DSRemote#23]
I am aware of #15 and #12 and it seems to be somehow similar.
But the fact that there is also no connection via LAN makes me believe that it is not only related to the EHCI USB host controller mentionend in https://github.com/Teuniz/DSRemote/issues/12#issuecomment-283940080

```
$ ./dsremote               
Disconnected from device
tmc_dev write: *IDN?
Disconnected from device
tmc_lan write: *IDN?
Disconnected from device
```
Host
```
Ubuntu 16.04.3 LTS
Linux pc 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Scope
```
DS1104Z
SW: 00.04.04.sp3 
```

Is there any way to debug it?

**Comment by Teuniz** [comment]
It's weird because there's no message about what's going on.
If you look at the source, if anything goes wrong, it prints an error message.
Use Wireshark to see what's going on on your LAN. Check the reponse coming from the scope.

**Comment by momu** [comment]
I solved the mystery:

1. When there is a USB connection, the LAN connection is disabled. 
1. USB3 ports are not working well with the Rigol.

Solution:
Just use a USB2 port.
