### ISSUE TITLE
Cannot Connect/Read From Device

### ISSUE THREAD

**Issue by WinWizard** [Teuniz/DSRemote#25]
Scope: DS1054Z (unlocked and shows DS1104Z in about)
Scope FW: 4.04 SP3
OS: Xubuntu 16.04LTS

I am unable to connect to the scope both by LAN or USB.
The console just outputs:
```
tmc_lan write: *IDN?
Disconnected from device
tmc_dev write: *IDN?
Disconnected from device
```
The program just tells me I cannot connect. I have followed all build instructions and have added the udev rule and i am part of the usbtmc group. I have also tried running as root to no avail.

**Comment by Teuniz** [comment]
There should be a pop-up message window that describes the cause of the error.
What does it say?

**Comment by WinWizard** [comment]
The only popup I receive is cannot connect. That's is all it says.

**Comment by Teuniz** [comment]
Can you open a console and use telnet to connect to the scope?
open a console and enter:

telnet 192.168.1.17 5555     (modify the IP-address if necessary)

Check connectivity using the command:

*IDN?

The scope will respond with brand, model and serial number.

Let me know if this works and copy/paste the response of the *IDN? command here.

Also, what is the firmware version of your scope?

**Comment by WinWizard** [comment]
I will try that when I get home from the gym. I am on 4.04 SP3

**Comment by WinWizard** [comment]
I tried the IDN command and got nothing over ethernet so its something on my end for that. I did however realize i had plugged the usb into the usb3 port (which doesn't work). I apologize for wasting your time it now works. Thanks for the help.
