### ISSUE TITLE
Can't read screen via USBTSC, DS1054Z v00.04.04 (June 2016 FW), LAN Works fine

### ISSUE THREAD

**Issue by GeoffMaciolek** [Teuniz/DSRemote#3]
To note - screen reading works 100% fine over the network interface, and the other scope functions that get engaged during the connection seem to do what's expected.  The following dialog pops up when connecting via USBTSC:

>An error occurred while reading screen data from device.
>File screen_thread.cpp line 608 [OK]

The console displays the following:

```
tmc_dev write: :DISP:GRAD:TIME?
tmc_dev write: :MATH:FFT:SPL?
tmc_dev write: :MATH:DISP?
tmc_dev write: :MATH:FFT:UNIT?
tmc_dev write: :MATH:FFT:SOUR?
tmc_dev write: :MATH:FFT:HSC?
tmc_dev write: :MATH:FFT:HCEN?
tmc_dev write: :MATH:OFFS?
tmc_dev write: :MATH:SCAL?
Can not read from device.
```

The console displays all the same stuff when connecting via LAN, aside from the `Can not read from device.` line

System is Arch Linux, 64 bit

Incidentally, the release notes and filenames indicte that this formware is `v00.04.04.00.07` - rather than the v00.04.04 as displayed on the scope's UI, but there doesn't appear to be any other 04.04 release besides ...00.07.

Also worth noting - the DS1054Z_screen_capture (LAN image capture) Python program does *not* work - and it did when I was on 00.04.03 SP2. It complainins about  However, DSRemote couldn't use USB at all when I was on 00.04.04 SP2.  Go figure!

**Comment by Teuniz** [comment]
The firmware update version 00.04.04.00.07 breaks the usbtmc interface.
I'll try to investigate to see what's going on.

**Comment by Teuniz** [comment]
There's a fix. Just pull again and recompile.

**Comment by LokiChaos** [comment]
Working for me.  Thanks!
