### ISSUE TITLE
Inconsistend Code formatting

### ISSUE THREAD

**Issue by zarath** [Teuniz/DSRemote#9]
Code readability is poor as space and
empty lines are inconsitently cluttered
all over the code.

Any concerns to run clang-format over
*.h and *.cpp files?

e.g.:

  clang-format --style=LLVM -i *.h *.cpp

**Comment by Teuniz** [comment]
For me, the readability is optimal.
Changing the style will make it harder for me to read.
And because I have to write and maintain it, readability needs to be optimal for me.
